#!/usr/bin/env bash

# One letter aliases
alias c="clear"
alias e="nvim"
alias l="ls --color=auto -A"
alias s="sudo"

# Two letter aliases
alias aI="sudo apt install --yes"
alias aR="sudo apt autoremove"
alias aU="sudo apt upgrade --yes"
alias ai="sudo apt install"
alias ar="sudo apt remove"
alias au="sudo apt update"
alias ls="ls --color=auto -A"
alias vi="nvim"

# Three letter aliases
alias cco="gcc --std=c2x -lm -Wall -Werror -o"
alias dco="dmd -de -w -unittest"
