#!/usr/bin/env bash

alias aI="sudo apt install --yes"
alias aR="sudo apt autoremove"
alias aU="sudo apt upgrade --yes"
alias ai="sudo apt install"
alias ar="sudo apt remove"
alias au="sudo apt update"
alias cc="gcc --std=c2x -lm -Wall -Werror -o"
alias c="clear"
alias e="nvim"
alias l="ls -A --color=auto"
alias s="sudo"
